[난정] 1주차 수요일 PR
codesquad-members-2022/fe-vm pull request #11
Opened 2022-05-11 08:09 UTC by nanjeong

안녕하세요, 난정입니다.

## 데모
![금액 입력 데모](https://user-images.githubusercontent.com/62249058/167798635-3806f7af-b031-4376-a86b-e241b8640b51.gif)

## 진행 사항
* 사용자 금액 입력
    * 금액을 입력한 후 엔터를 치면 자판기에 돈이 들어간 것으로 가정
    * 사용자가 입력한 금액이 존재하지 않는 화폐 단위면 존재하는 화폐 단위 중 가장 가까운 금액으로 바꿔줬습니다.
       (예) 사용자의 지갑에 100원이 있을 때, 150원 입력 -> 100원,  
       사용자의 지갑에 100원은 없고 50원과 500원이 있을 때, 150원 입력 -> 50원으로 변환
    * 자판기에 돈이 들어가면 지갑에도 반영
    * 구입할 수 있는 상품 border 빨갛게 표시
    * 사용자 입력 기록판에 기록

2022-05-12 06:00 UTC, ocipap commented
금일 저녁에 리뷰 남기도록 할께요!

2022-05-12 14:29 UTC, ocipap commented on src/components/product/Product.jsx
> +                <ProductContainer key={uuid()}>
uuid 는 data/products.js 에서 만들어 주는 것이 좋아보이네요!

```
const products = [...].map(product => ({ ...product, id: uuid() }))

// ...
<ProductContainer key={product.id}>



```

2022-05-12 14:38 UTC, ocipap commented on src/components/product/Products.jsx
> +    );
Products 와 Product 에서 사용하는 props 의 이름은 같은데, Products 에서 로직을 수행시킨 결과물을 넘기고 있네요

moneyInVendingMachine 이라는 값이
Product 에서는 reduce 한 값, Products 에서는 unit 을 포함하고 있는 배열로 사용되고 있는 것 같아서
값의 의미를 맞추면 좋을 것 같아요!

2022-05-12 14:39 UTC, ocipap commented on src/components/recordBoard/RecordBoard.jsx
> +                <p key={uuid()}>{r}</p>
products 과 동일하게 uuid 로직을 record 에서 받아오면 좋을 것 같아요!

2022-05-12 14:43 UTC, ocipap commented on src/routes/home/Home.jsx
> +    const [moneyInVendingMachine, setMoneyInVendingMachine] = useState({});
요 상태를 context 로 빼보는 것은 어떨까요?
여러 컴포넌트에서 해당 상태를 사용하고 있어서, props 를 많이 사용하는 것 같아서요!

2022-05-12 14:45 UTC, ocipap commented on src/routes/home/Home.jsx
> +            <Outlet
Outlet 이라는 것을 처음 봐서 혹시 역할이 어떻게 될까요??

2022-05-12 14:49 UTC, ocipap requested changes
Outlet 이라는 신기한 기능에 대해서도 알게되었네요!
wallet 에 대한 관심사를 context 를 통해서 관리하면, 뷰단위 로직을 조금 더 통일 할 수 있을 것 같습니다. 

혹시 하시다가 질문이 있으시면 편하게 DM 보내주세요!

2022-05-12 23:55 UTC, nanjeong commented on src/routes/home/Home.jsx
> +    const [moneyInVendingMachine, setMoneyInVendingMachine] = useState({});
학습한 후 적용하겠습니다!

2022-05-13 00:06 UTC, nanjeong commented on src/routes/home/Home.jsx
> +            <Outlet
중첩된 `<Route>`를 사용할 때 부모 라우트에서 `<Outlet>`을 작성한 부분에 자식 라우트가 들어갑니다.

2022-05-13 02:10 UTC, ocipap commented on src/routes/home/Home.jsx
> +            <Outlet
아하 이번 react router 에 이런 기능이 있었군요! 감사합니다!

2022-05-13 02:10 UTC, ocipap commented
다음 PR 을 위해 해당 PR 은 머지하도록 하겠습니다!

2022-05-13 02:10 UTC, merged